# appspec.yml

version: 0.0	# CodeDeploy 버전
os: linux
files:    
        - source: /	# CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 루트로 지정(전체파일)
          destination: /home/ec2-user/app/	# source에서 지정된 파일을 받을 위치, 이후 jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
          overwrite: yes
permissions:
  - object: /
    owner: root
    group: root
    mode: 740
    
hooks:
# 주의 할 점은 빈칸 yml파일 특성상 빈칸 개수를 중시해야하고 Tab을 쓰면 안된다는점
# AfterInstall앞은 2칸이다.
  AfterInstall:
# location은 프로젝트 기준으로 위치를 작성해준다!
    - location: ./restart.sh
# runas를 입력해주지 않으면 간혹 permission error가 날 수도
      runas: root
